name: haskell-fmt

on:
  push:
    branches:
      - "main"
      - "master"
  pull_request:
    branches:
      - "main"
      - "master"

jobs:
  hlint-check:
    name: Check Haskell lints
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Check Haskell lints
        uses: haskell-actions/hlint-scan@v1
        with:
          path: ./code/haskell
