name: Release Slides (PDF)

on:
  push:
    tags:
      - "*"

jobs:
  slides-release:
    name: "Release Slides"
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Typst
        uses: typst-community/setup-typst@v4

      - name: Compile slides EN
        run: typst compile slides/slides.typ slides/slides.pdf

      - name: Compile slides PT
        run: typst compile slides/slides-pt.typ slides/slides-pt.pdf

      - name: Release slides
        uses: ncipollo/release-action@v1
        id: release
        with:
          artifacts: "./slides/*.pdf"
