name: zig-fmt

on:
  push:
    branches:
      - "main"
      - "master"
  pull_request:
    branches:
      - "main"
      - "master"

jobs:
  clang-format:
    name: Check if zig code is formatted
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup zig
        uses: mlugg/setup-zig@v2

      - name: Check zig code format
        run: zig fmt --check ./code/zig/*.zig
